# Generated by Django 5.2.15 on 2026-06-12 15:50

import django.db.models.deletion
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('telegram_username', models.CharField(blank=True, max_length=64, verbose_name='Telegram username')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, help_text='Заполняется ботом после /start с инвайт-токеном.', null=True, unique=True, verbose_name='Telegram chat ID')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('guide_url', models.URLField(blank=True, verbose_name='Ссылка на гид / курс')),
                ('marketplace_url', models.URLField(blank=True, verbose_name='Ссылка на маркетплейс')),
                ('extra_links', models.JSONField(blank=True, default=list, verbose_name='Дополнительные ссылки')),
                ('status', models.CharField(choices=[('STUDYING', 'Обучается'), ('WAITING', 'Ожидает стажировку'), ('IN_PROGRESS', 'Проходит стажировку'), ('COMPLETED', 'Прошёл стажировку'), ('DROPPED', 'Отчислен')], default='STUDYING', max_length=20, verbose_name='Статус')),
                ('next_contact_at', models.DateField(blank=True, null=True, verbose_name='Следующий контакт')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('directions', models.ManyToManyField(blank=True, related_name='students', to='students.direction', verbose_name='Направления')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='TelegramInviteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=students.models._default_invite_token, max_length=40, unique=True, verbose_name='Токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('expires_at', models.DateTimeField(default=students.models._default_invite_expires_at, verbose_name='Истекает')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Инвайт-токен студента',
                'verbose_name_plural': 'Инвайт-токены студентов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='students_st_status_5e2210_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['next_contact_at'], name='students_st_next_co_063653_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['telegram_chat_id'], name='students_st_telegra_a3dadb_idx'),
        ),
    ]
