# Generated by Django 5.2.15 on 2026-06-12 15:50

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SENT_TO_COMPANY', 'Передали резюме'), ('IN_PROGRESS', 'Проходит стажировку'), ('COMPLETED', 'Успешно завершил'), ('REJECTED_BY_COMPANY', 'Отказ компании'), ('REJECTED_BY_STUDENT', 'Отказ студента')], default='SENT_TO_COMPANY', max_length=30, verbose_name='Статус')),
                ('sent_at', models.DateField(default=datetime.date.today, verbose_name='Дата передачи резюме')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='Дата начала стажировки')),
                ('planned_duration_days', models.PositiveSmallIntegerField(blank=True, help_text='Если пусто — алерт «превысил срок» не считаем.', null=True, verbose_name='Плановая длительность (дней)')),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Обновляется только через сервис change_placement_status.', verbose_name='Дата изменения статуса')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='companies.company', verbose_name='Компания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_placements', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='students.direction', verbose_name='Направление')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Связка студент ↔ компания',
                'verbose_name_plural': 'Связки студент ↔ компания',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='placements__status_050fcb_idx'), models.Index(fields=['status_changed_at'], name='placements__status__467dc2_idx')],
            },
        ),
    ]
