# Generated by Django 5.2.15 on 2026-06-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('contacts', models.TextField(blank=True, help_text='Свободный текст: имена, телефоны, telegram.', verbose_name='Контакты')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('hiring_status', models.CharField(choices=[('OPEN', 'Принимают'), ('CLOSED', 'Не принимают'), ('PAUSED', 'Пауза')], default='OPEN', max_length=20, verbose_name='Статус найма')),
                ('next_contact_at', models.DateField(blank=True, null=True, verbose_name='Следующий контакт')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('directions', models.ManyToManyField(blank=True, related_name='companies', to='students.direction', verbose_name='Направления')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['hiring_status'], name='companies_c_hiring__24f439_idx'), models.Index(fields=['next_contact_at'], name='companies_c_next_co_025991_idx')],
            },
        ),
    ]
