# Generated by Django 5.2.15 on 2026-06-12 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Обновляется только через сервис change_company_status.', verbose_name='Дата изменения статуса найма'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['status_changed_at'], name='companies_c_status__7c77f0_idx'),
        ),
    ]
