# Generated by Django 5.2.15 on 2026-06-12 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('placements', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('audience', models.CharField(choices=[('MANAGER', 'Менеджер'), ('STUDENT', 'Студент')], max_length=20, verbose_name='Аудитория')),
                ('text', models.TextField(help_text='Поддерживает подстановки {student_name}, {company_name}, {days}, {direction}.', verbose_name='Текст')),
                ('inline_buttons', models.JSONField(blank=True, default=list, help_text='Список вида [{"label": "Всё ок", "callback": "survey_ok"}].', verbose_name='Inline-кнопки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Шаблон сообщения',
                'verbose_name_plural': 'Шаблоны сообщений',
                'ordering': ['audience', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('RUNNING', 'Отправляется'), ('DONE', 'Завершена'), ('FAILED', 'Ошибка')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('recipients', models.ManyToManyField(related_name='broadcast_jobs', to='students.student', verbose_name='Получатели')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('trigger_type', models.CharField(choices=[('PLACEMENT_STATUS_STALE', 'Связка зависла в статусе'), ('PLACEMENT_DURATION_EXCEEDED', 'Превышен срок стажировки'), ('COMPANY_PAUSED_STALE', 'Компания долго на паузе'), ('STUDENT_STATUS_PERIODIC', 'Периодический опросник студента')], max_length=30, verbose_name='Тип триггера')),
                ('target_status', models.CharField(blank=True, help_text='Зависит от типа триггера. Может быть пустым.', max_length=30, verbose_name='Целевой статус')),
                ('days_threshold', models.PositiveSmallIntegerField(help_text='Через сколько дней с момента события срабатывает правило.', verbose_name='Порог (дней)')),
                ('recurring_every_days', models.PositiveSmallIntegerField(blank=True, help_text='Если пусто — правило одноразовое для объекта.', null=True, verbose_name='Повторять каждые N дней')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='push_rules', to='notifications.messagetemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Правило автопуша',
                'verbose_name_plural': 'Правила автопушей',
                'ordering': ['trigger_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='notificatio_content_d9c53f_idx')],
            },
        ),
        migrations.CreateModel(
            name='BroadcastDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('SENT', 'Отправлено'), ('BLOCKED', 'Заблокировал бота'), ('NO_CHAT_ID', 'Не подписан на бота'), ('FAILED', 'Ошибка')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('error_text', models.TextField(blank=True, verbose_name='Ошибка')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='broadcast_deliveries', to='students.student', verbose_name='Студент')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.broadcastjob', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
                'indexes': [models.Index(fields=['job', 'status'], name='notificatio_job_id_203327_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='ID объекта')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', '-created_at'], name='notificatio_content_ab7f7e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ManualContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата контакта')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('broadcast_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_contacts', to='notifications.broadcastjob', verbose_name='Контекст рассылки')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_contacts', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Ручной контакт',
                'verbose_name_plural': 'Ручные контакты',
                'ordering': ['-contacted_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'broadcast_job', 'manager'), name='uniq_manual_contact')],
            },
        ),
        migrations.CreateModel(
            name='PushSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('recipient_chat_id', models.BigIntegerField(verbose_name='Куда уходило')),
                ('response_callback', models.CharField(blank=True, max_length=50, verbose_name='Ответ (callback)')),
                ('response_at', models.DateTimeField(blank=True, null=True, verbose_name='Время ответа')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_sent', to='companies.company', verbose_name='Компания')),
                ('placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_sent', to='placements.placement', verbose_name='Связка')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_pushes', to='notifications.pushrule', verbose_name='Правило')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_sent', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Отправленный автопуш',
                'verbose_name_plural': 'Отправленные автопуши',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['sent_at'], name='notificatio_sent_at_d1e5a8_idx'), models.Index(fields=['rule', 'sent_at'], name='notificatio_rule_id_086d1c_idx'), models.Index(fields=['rule', 'placement'], name='notificatio_rule_id_660160_idx'), models.Index(fields=['rule', 'company'], name='notificatio_rule_id_85c3cd_idx'), models.Index(fields=['rule', 'student'], name='notificatio_rule_id_5f61c5_idx')],
            },
        ),
    ]
